sw_ranking:
  arena_df_path:
  arena_embedding_path:
  strong_model:
  weak_model:
causal_llm:
  model_checkpoint_path:
  system_message:
  classifier_message:
  model_config:
    model_id:
    model_type:
    special_tokens:
    num_outputs:
bert:
  model_path:
matrix_factorization:
  checkpoint_path:
  hidden_size:
  strong_model:
  weak_model:
