[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "routellm"
version = "0.0.1"
readme = "README.md"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
	'importlib-metadata; python_version<"3.10"',
	'pyyaml',
	'pydantic',
	'numpy',
	'pandas',
	'torch',
	'scikit-learn',
	'tqdm',
	'openai',
	'transformers',
	'tiktoken',
	'sglang',
	'pandarallel',
	'matplotlib',
	'datasets'
]

[project.optional-dependencies]
serve = ["fastapi", "shortuuid", "uvicorn"]
dev = ["black", "isort", "pre-commit"]

[tool.isort]
profile = "black"

[tool.setuptools.packages.find]
exclude = ["assets*"]

[tool.wheel]
exclude = ["assets*"]
